### ISSUE TITLE
update database and show colors

### ISSUE THREAD

**Issue by ibarraespinosa** [ibarraespinosa/cptcity#10]
fd <- function(x) {
  oldpar <- par(no.readonly = TRUE)
  par(mfrow =  c(10,10), mar =c(0,0,0,0))
  for(i in seq_along(x)){
    image(matrix(1:100), col = cpt(x[i]), frame = F, xaxt = "n", yaxt = "n")
    text(x = 50, y = 1, labels = i)
  } 
  on.exit(par(oldpar))
}

find_cpt("sky")[2]
fd(find_cpt("sky")[1])
image(matrix(1:10))

I need to define the dimensions of mfrow automatically according to length of vector

**Comment by ambarja** [comment]
@ibarraespinosa  Is possible add new color palettes, for example mako, rocket , positron, turbo and civicidis or only is about of the page of cptcity colors? Because this page maybe now I don't have support and maybe never update.

**Comment by ibarraespinosa** [comment]
hello @ambarja, yes, it can be done without any problem. The data.frame with RGB is here https://github.com/ibarraespinosa/cptcity/blob/master/R/sysdata.rda.

Then, if you have the data.frames, you could PR the new colour palettes. I might make modifications on find_cpt but the package has few functions, so it wont be a problem.

Thanks for reaching out. Actually, the new CPT archive has over 14000 colour palettes and I need to find some time to update it.

Alternatively, you could email me the matrices and I will add them.

Proceed as you wish and thanks again.

**Comment by ibarraespinosa** [comment]
https://github.com/ibarraespinosa/cptcity/commit/3e7070af1c8a0ce8b38b750820d3f5889dcf0eb1

**Comment by ibarraespinosa** [comment]
https://github.com/ibarraespinosa/cptcity/commit/3e7070af1c8a0ce8b38b750820d3f5889dcf0eb1
