### ISSUE TITLE
Minor spelling issue

### ISSUE THREAD

**Issue by ghost** [ibarraespinosa/cptcity#3]
A selection of colours is a _palette_, while a _pallet_ is a wooden support for transporting things.
![single-pallet](https://user-images.githubusercontent.com/3464626/37115391-eb5c3a8e-2242-11e8-8b25-ce0c98b7e308.jpg)

I don't think pallete is a word in English at all.

**Comment by ibarraespinosa** [comment]
Hey Jim, Thanks for clarifying. Sometimes I think I'm dyslexic. Anyway, I fixed all your observations, many thanks!
