### ISSUE TITLE
add option to generate rev palettes

### ISSUE THREAD

**Issue by ibarraespinosa** [ibarraespinosa/cptcity#6]

**Comment by Schuch666** [comment]
sim!!!! todos querem!!

**Comment by ibarraespinosa** [comment]
vai ser com interna reversão dos data.frames, para poder usar com todos os tipos de objetos de R

**Comment by ibarraespinosa** [comment]
![rplot01](https://user-images.githubusercontent.com/27447280/53952592-1ccb2880-410c-11e9-8d2e-a0b85a4ae3d3.png)

**Comment by ibarraespinosa** [comment]
![rplot02](https://user-images.githubusercontent.com/27447280/53952837-e2ae5680-410c-11e9-8783-60d7600aa771.png)
